# Generated by Django 3.1.7 on 2021-03-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='questions',
            field=models.ManyToManyField(blank=True, to='jobs.Question'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
