# Generated by Django 3.0.3 on 2021-03-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210327_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='jobs.Job'),
        ),
    ]
