# Generated by Django 3.1.7 on 2021-03-27 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210327_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.URLField(default=uuid.uuid4, unique=True),
        ),
    ]
