# Generated by Django 3.1.7 on 2021-03-27 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210327_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.URLField(default=uuid.uuid1, unique=True),
        ),
    ]
